#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BeatSync.Resource", IsApplication=true)]

namespace BeatSync
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int button = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int icon_app = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int icon_back = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int icon_bluetooth = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int icon_note = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int icon_pairing01 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int icon_pairing02 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int icon_pause = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int icon_play = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int icon_settings = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int txt_pair = 2130837515;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050002
			public const int BPM = 2131034114;
			
			// aapt resource value: 0x7f05000e
			public const int btnClearCache = 2131034126;
			
			// aapt resource value: 0x7f05000d
			public const int btnDone = 2131034125;
			
			// aapt resource value: 0x7f050005
			public const int btnMain = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int imgBack = 2131034119;
			
			// aapt resource value: 0x7f050000
			public const int imgPlaylist = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int imgSettings = 2131034113;
			
			// aapt resource value: 0x7f050009
			public const int lvSongs = 2131034121;
			
			// aapt resource value: 0x7f05000b
			public const int npAgePicker = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int pbProgressBar = 2131034122;
			
			// aapt resource value: 0x7f050003
			public const int txtBPM = 2131034115;
			
			// aapt resource value: 0x7f050008
			public const int txtPlaylist = 2131034120;
			
			// aapt resource value: 0x7f05000c
			public const int txtRange = 2131034124;
			
			// aapt resource value: 0x7f050004
			public const int txtSong = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int txtStatus = 2131034118;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Playlist = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Settings = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
